#include "Dialect/ScheduleDialect/ScheduleDialectDialect.h"
#include "Dialect/ScheduleDialect/ScheduleDialectOpsDialect.cpp.inc"
#include "Dialect/SpecHLS/SpecHLSDialect.h"
#include "Dialect/SpecHLS/SpecHLSOps.h"
#include "Dialect/SpecHLS/SpecHLSUtils.h"
#include "Transforms/Passes.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/HW/HWOpInterfaces.h"
#include "circt/Dialect/HW/HWOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"

#include "mlir/CAPI/Registration.h"

#ifdef __cplusplus
extern "C" {
#endif
void initSpecHLS();
MlirModule parseMLIR(const char *mlir);
void destroyMLIR(MlirModule module);
void pass(const char *mlir);
#ifdef __cplusplus
}
#endif

/* Autogenerated by mlir-tblgen; don't manually edit. */

#include "mlir-c/Pass.h"

#ifdef __cplusplus
extern "C" {
#endif

// Registration for the entire group
// Registration for the entire group
//MLIR_CAPI_EXPORTED void createSchedulePass(void);
//MLIR_CAPI_EXPORTED void createMobilityPass(void);
//MLIR_CAPI_EXPORTED void createConfigurationExcluderPass(void);

MLIR_CAPI_EXPORTED void registerSchedulePass(void);
MLIR_CAPI_EXPORTED void registerMobilityPass(void);
MLIR_CAPI_EXPORTED void registerConfigurationExcluderPass(void);

#define DECLARE_GECOS_API_PASS(name, pass) \
  MlirPass mlirCreate##pass(); \
  bool name(MlirModule module) ;


DECLARE_GECOS_API_PASS(scheduleMLIR, SchedulePass)
DECLARE_GECOS_API_PASS(canonicalizeMLIR, TransformsCanonicalizer)
DECLARE_GECOS_API_PASS(mobilityMLIR, MobilityPass)

DECLARE_GECOS_API_PASS(configurationExcluderMLIR, ConfigurationExcluderPass)

DECLARE_GECOS_API_PASS(exportVitisHLS, ExportVitisHLS)
DECLARE_GECOS_API_PASS(yosysOptimizer, YosysOptimizerPass)
DECLARE_GECOS_API_PASS(groupControl, GroupControlNodePass)
DECLARE_GECOS_API_PASS(groupGammas, GroupGammaNodesPass)
DECLARE_GECOS_API_PASS(factorGammaInputs, FactorGammaInputsPass)
DECLARE_GECOS_API_PASS(mergeLUTs, MergeLookUpTablesPass)
DECLARE_GECOS_API_PASS(mergeGammas, MergeGammasPass)
DECLARE_GECOS_API_PASS(mergeGammas, MergeGammasPass)
DECLARE_GECOS_API_PASS(lowerGecosOspToComb,LowerGecosOpsToCombPass)

DECLARE_GECOS_API_PASS(eliminateRedundantGammaInputs,
                      EliminateRedundantGammaInputsPass)
DECLARE_GECOS_API_PASS(inlineModule, InlineModulesPass)

#ifdef __cplusplus
}
#endif