//
// Created by Steven on 02/01/2024.
//

#ifndef SPECHLS_DIALECT_INLINEOPTIMIZEDMODULES_H
#define SPECHLS_DIALECT_INLINEOPTIMIZEDMODULES_H

class InlineOptimizedModules {};

#endif // SPECHLS_DIALECT_INLINEOPTIMIZEDMODULES_H
